# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
palette = "catppuccin_mocha"

# Inserts a blank line between shell prompts
add_newline = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
format = "[$symbol ]($style)"

[nodejs]
disabled = true
format = "[$symbol ]($style)"
[python]
disabled = true
format = "[$symbol ]($style)"

[battery]
full_symbol = 'üîã '
charging_symbol = '‚ö°Ô∏è '
discharging_symbol = 'üíÄ '

[[battery.display]]
threshold = 90
style = 'bold yellow'
discharging_symbol = 'üí¶ '

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

format = """
[‚ï≠](fg:current_line)\
$os\
$directory\
$git_branch\
$cmd_duration\
$shell\
$time\
$username\
$line_break\
$character\
"""

[shell]
format = '(fg:current_line)(fg:blue)(fg:primary bg:blue)(fg:blue bg:box)(fg:foreground bg:box)(fg:box)'
unknown_indicator = 'shell'
powershell_indicator = 'powershell'
fish_indicator = 'fish'
disabled = false

[character]
format = """
[‚ï∞‚îÄ$symbol](fg:current_line) """
success_symbol = '[Œª](fg:bold white)'
error_symbol = '[√ó](fg:bold red)'
